args:
  training_args:
    train_data: ./data/data_train.csv
    sample_data: ./data/sampleSubmission.csv
    num_users: 10000
    num_items: 1000
    test_size: 0.1
    test_save_dir: ./output/logs/output
    model_load_path: ./output/models
    model_save_path: ./output/models
    random_seed: 42
    device: "cpu"
    imputation: "mean"
    normalization: "zscore"
    min_rate: 1
    max_rate: 5
  experiment_args:
    model_name: "als"
    save_predictions: False
    predictions_folder: ./output/predictions
    generate_submissions: True
    submission_folder: ./output/submission
    verbose: True
  svd_args:
    svd_rank: 9
  als_args:
    svd_rank: 9
    imputation: "zero"
    num_iterations: 20
    reg_param: 0.15
    latent_dim: 3
  isvd_args:
    isvd_iter: 15
    isvd_type: "nnr" # svp: Singular Value Projection, nnr: Nuclear Norm Relaxation
    isvd_eta: 0.3
    isvd_rank: 9
    isvd_shrinkage: 38
  svdpp_args:
    n_factors: 3
    lr_all: 0.003
    n_epochs: 100
    reg_all: 0.05