args:
  training_args:
    train_data: ./data/data_train.csv
    sample_data: ./data/sampleSubmission.csv
    num_users: 10000
    num_items: 1000
    test_size: 0.1
    test_save_dir: ./output/logs/output
    model_load_path: ./output/models
    model_save_path: ./output/models
    random_seed: 42
    device: "cpu"
    imputation: "zero"
    normalization: "zscore"
    min_rate: 1
    max_rate: 5

  experiment_args:
    model_name: "isvd"
    generate_submissions: False
    submission_folder: ./output/submission
    verbose: True

  svd_args:
    rank: 9
  als_args:
    svd_rank: 9
    imputation: "zero"
    num_iterations: 20
    reg_param: 0.15
    latent_dim: 3
  isvd_args:
    imputation: "mean"
    num_iterations: 15
    type: "nnr" # svp: Singular Value Projection, nnr: Nuclear Norm Relaxation
    eta: 0.3
    rank: 9
    shrinkage: 38
  svdpp_args:
    n_factors: 3
    lr_all: 0.003
    n_epochs: 100
    reg_all: 0.05