args:
  training_args:
    train_data: ./data/data_train.csv
    sample_data: ./data/sampleSubmission.csv
    num_users: 10000
    num_items: 1000
    test_size: 0.1
#    test_save_dir: ./output/logs/output
#    model_load_path: ./output/models
#    model_save_path: ./output/models
    random_seed: 42
    device: "cpu"
    min_rate: 1
    max_rate: 5

  experiment_args:
    model_name: "ensemble"
    model_instance_name: "svdpp"
    generate_submissions: True
    submission_folder: ./output/submission
    verbose: True

  svd_args:
    imputation: "zero"
    rank: 9
  als_args:
    imputation: "zero"
    num_iterations: 20
    svd_rank: 9
    reg_param: 0.15
    latent_dim: 3
  isvd_args:
    imputation: "mean"
    num_iterations: 15
    type: "svp" # svp: Singular Value Projection, nnr: Nuclear Norm Relaxation
    eta: 0.3
    rank: 9
    shrinkage: 38
  svdpp_args:
    n_factors: 3
    lr_all: 0.003
    n_epochs: 100
    reg_all: 0.05
  bfm_args:
    algorithm: "regression" # regression, oprobit
    variational: False
    iteration: 500 # 500 # 512
    dimension: 32
    use_iu: True
    use_ii: True
  ncf_args:
    EPOCHS: 20
    BATCH_SIZE: 128
    n_factors: 10
    learning_rate: 0.001
    train_file: ./data/ncf/actual.csv
    save_file: ./data/ncf/submission_neural.csv
    all_predictions_file: ./data/ncf/predictions_alle.csv
  vae_args:
    num_iterations: 2000
    batch_size: 1024
    hidden_dim: 256
    latent_dim: 32
    dropout: 0.5
    lr: 0.025
    weight_decay: 0
    gamma: 0.997
    beta: 0.2
  ensemble_args:
    fold_number: 5
    shuffle: True
    regressor: 'ElasticNet'
    data_ensemble: './output/data_ensemble/'
    models: ["bfm_op_novar_500_32", "bfm_reg_novar_500_32"] # "bfm_reg_var_500_32", "bfm_op_novar_500_32", "bfm_reg_novar_500_32"
  cv_args:
    save_full_pred: False # True
