args:
  training_args:
    train_data: ./data/data_train.csv
    test_size: 0.1
    test_save_dir: ./logs/output
    model_load_path: ./models
    model_save_path: ./models
    random_seed: 42
    device: "cpu"
    imputation: "mean"
    normalization: "zscore"
  experiment_args:
    model_name: "isvd"
    save_predictions: False
    predictions_folder: "predictions"
  svd_args:
    svd_rank: 9
  isvd_args:
    num_iter: 15
    shrinkage: 38







